service: singularity-health-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 1024
  timeout: 30
  environment:
    DEBUG: "False"
    SECRET_KEY: ${env:SECRET_KEY, 'your-secret-key-here'}
    DB_NAME: ${env:DB_NAME, 'users'}
    DB_USER: ${env:DB_USER, 'root'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'Root123#4'}
    DB_HOST: ${env:DB_HOST, 'db-users.c0p4qigkiy8m.us-east-1.rds.amazonaws.com'}
    DB_PORT: ${env:DB_PORT, '3306'}
    USE_S3: "False" # Desactivamos S3 por ahora
    # Variables para corregir las URLs en Lambda
    SCRIPT_NAME: "" # Para que Django genere URLs correctas
    BASE_URL: "https://1afs3bt7ti.execute-api.us-east-1.amazonaws.com"
  httpApi:
    cors: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    # La configuración de CORS se maneja a nivel de API Gateway o a través de Django

  migrate:
    handler: migrate.handler
    description: "Ejecuta las migraciones de Django"
    timeout: 60 # Las migraciones pueden llevar más tiempo

custom:
  wsgi:
    app: singularity_health.wsgi.application
    packRequirements: false
    # Configurar el manejo de rutas para que funcione con Django
    apiGateway: true
    # Para que las redirecciones funcionen correctamente
    removeBasePath: false

  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: true
    slim: true
    strip: false
    layer: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - "!venv/**"
    - "!node_modules/**"
    - "!.git/**"
    - "!.github/**"
    - "!scripts/**"
    - "!tests/**"
    - "!*.md"
    - "!.gitignore"
    - "!.env*"
    - "!zappa_settings.json"
