name = "singularity-health"
compatibility_date = "2024-03-23"

[site]
bucket = "dist"

[build]
command = "npm run build"
upload.format = "directory"
upload.dir = "dist"

[env.production]
name = "singularity-health"

[env.development]
name = "singularity-health-dev" 